### PR TITLE
Unrevert "Prefix fields of nested struct with tag of nested struct + ."

### PR DESCRIPTION
**Pull request by acls**
This undoes the breaking changes knowingly caused in #210 and also fixes the minor custom unmarshaller issue that it mentions.

### CODE REVIEW

**Comment by pikanezi** [comment]
thanks and sorry for the inconvenience

**Comment by acls** [comment]
Thanks and no worries. And thank you for all the work you've done on this go module.

**Comment by acls** [comment]
@ieure Can you test the latest version to see if this caused any breaking changes?

**Comment by ieure** [comment]
@acls I cannot.  I no longer work for the company I was employed by when I reported the issue, so I have no access to the code which triggered the unwanted behavior.

**Pull request merged**
